language: ruby
rvm:
  - '1.9.3-p551'
  - '2.2.6'
  - '2.3.3'
  - '2.4.0'
before_install:
  - sudo apt-get install cimg-dev
  - gem update bundler
before_script: (cd ext/phamilie && ruby extconf.rb && make)
script: bundle exec rspec
matrix:
  include:
    - env: CHECK_RUBIES=✓
      rvm: '2.4.0'
      script: bundle exec travis_check_rubies --exclude 2.0,2.1
