language: ruby
rvm:
  - '1.9.3-p551'
  - '2.2.10'
  - '2.3.8'
  - '2.4.6'
  - '2.5.5'
  - '2.6.3'
before_install:
  - sudo apt-get install cimg-dev
  - gem install bundler || gem install bundler --version '< 2'
before_script: (cd ext/phamilie && ruby extconf.rb && make)
script: bundle exec rspec
matrix:
  include:
    - env: CHECK_RUBIES=✓
      rvm: '2.6.3'
      script: bundle exec travis_check_rubies
